const fs = require('fs');
const path = require('path');

const distDir = path.join(__dirname, '..', 'dist');
const outFile = path.join(distDir, '_embedded.cjs');

function walkDir(dir) {
  const files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkDir(full));
    } else {
      files.push(full);
    }
  }
  return files;
}

const allFiles = walkDir(distDir).filter(f => !f.endsWith('_embedded.cjs'));

const assets = {};
for (const f of allFiles) {
  const rel = path.relative(distDir, f).replace(/\\/g, '/');
  assets[rel] = fs.readFileSync(f).toString('base64');
}

const code = `// Auto-generated by embed-assets.cjs
const __assets = ${JSON.stringify(assets, null, 2)};

if (typeof module !== 'undefined') {
  module.exports = __assets;
}
`;

fs.writeFileSync(outFile, code, 'utf-8');
console.log(`Embedded ${allFiles.length} assets into ${outFile}`);
